unet:
  _target_: unet.UNetModel
  _partial_: true
  model_channels: 128
  num_res_blocks: 2
  attention_resolutions:
    - 4
    - 8
  dropout: 0.0
  channel_mult:
    - 1
    - 2
    - 4
    - 8
  num_heads: 8
  num_classes: 10 # 10 classes for MNIST label condition or None for unconditional
  resblock_updown: true